CREATE ROLE IF NOT EXISTS TRANSFORM;

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH;

CREATE DATABASE IF NOT EXISTS MOVIELENS;
CREATE SCHEMA IF NOT EXISTS MOVIELENS.RAW;
CREATE SCHEMA IF NOT EXISTS MOVIELENS.DEV;

CREATE USER IF NOT EXISTS dbt
    PASSWORD = 'dbtPassword123'
    LOGIN_NAME = 'dbt'
    MUST_CHANGE_PASSWORD = FALSE
    DEFAULT_WAREHOUSE = 'COMPUTE_WH'
    DEFAULT_ROLE = TRANSFORM
    DEFAULT_NAMESPACE = 'MOVIELENS.RAW'
    COMMENT = 'dbt user used for data transformation';
GRANT ROLE TRANSFORM TO USER dbt;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;

GRANT USAGE ON DATABASE MOVIELENS TO ROLE TRANSFORM;

GRANT USAGE ON SCHEMA MOVIELENS.RAW TO ROLE TRANSFORM;
GRANT CREATE TABLE ON SCHEMA MOVIELENS.RAW TO ROLE TRANSFORM;
GRANT CREATE VIEW  ON SCHEMA MOVIELENS.RAW TO ROLE TRANSFORM;

GRANT ALL ON ALL TABLES IN SCHEMA MOVIELENS.RAW TO ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA MOVIELENS.RAW TO ROLE TRANSFORM;

-- DEV schema privileges
GRANT USAGE ON SCHEMA MOVIELENS.DEV TO ROLE TRANSFORM;
GRANT CREATE TABLE ON SCHEMA MOVIELENS.DEV TO ROLE TRANSFORM;
GRANT CREATE VIEW  ON SCHEMA MOVIELENS.DEV TO ROLE TRANSFORM;
GRANT SELECT ON ALL TABLES IN SCHEMA MOVIELENS.DEV TO ROLE TRANSFORM;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MOVIELENS.DEV TO ROLE TRANSFORM;
